# Generated by Django 4.1.7 on 2023-02-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='woe',
            name='title_kz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='woe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='woe',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='woe',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
