# Generated by Django 4.1.7 on 2023-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
