# Generated by Django 4.1.7 on 2023-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_alter_woe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
