# Generated by Django 4.1.7 on 2023-02-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_ch_woe_title_kz_alter_woe_id_alter_woe_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CH',
        ),
    ]
