# Generated by Django 4.1.7 on 2023-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_delete_ch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
