# Generated by Django 4.1.7 on 2023-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_alter_woe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
