# Generated by Django 4.1.7 on 2023-02-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_ch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woe',
            name='title_kz',
        ),
    ]
