# Generated by Django 4.1.7 on 2023-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_remove_woe_title_kz'),
    ]

    operations = [
        migrations.AddField(
            model_name='woe',
            name='title_kz',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
