# Generated by Django 4.1.7 on 2023-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_woe_title_kz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ch',
            name='text_kz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='woe',
            name='text_kz',
            field=models.TextField(default='', null=True),
        ),
    ]
